import 'dotenv/config'
import express from 'express'
import cookieParser from 'cookie-parser'
import bcrypt from 'bcryptjs'
import Database from 'better-sqlite3'
import crypto from 'node:crypto'
import path from 'node:path'
import fs from 'node:fs'

const app=express(); app.use(express.json({limit:'1mb'})); app.use(cookieParser())
const dataDir=path.resolve('data'); fs.mkdirSync(dataDir,{recursive:true})
const db=new Database(path.join(dataDir,'app.sqlite')); db.pragma('journal_mode = WAL')
db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('accountant','admin')),password_hash TEXT NOT NULL,disabled INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS journal_entries(id TEXT PRIMARY KEY,data TEXT NOT NULL,created_at INTEGER NOT NULL);`)
const uid=()=>crypto.randomUUID(), now=()=>Date.now(); const email=process.env.ADMIN_EMAIL||'admin@example.com', password=process.env.ADMIN_PASSWORD||'ChangeMe123!'
if(!db.prepare('SELECT 1 FROM users WHERE email=?').get(email)) db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,?)').run(uid(),email,'Администратор','admin',bcrypt.hashSync(password,12),0,now())
type Req=express.Request&{user?:any}; function auth(req:Req,res:express.Response,next:express.NextFunction){const u=req.cookies.sid&&db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?').get(req.cookies.sid,now()) as any;if(!u||u.disabled)return res.status(401).json({error:'Требуется авторизация'});req.user=u;next()} function isAdmin(req:Req,res:express.Response,next:express.NextFunction){if(req.user.role!=='admin')return res.status(403).json({error:'Недостаточно прав'});next()}
const pub=(u:any)=>({id:u.id,email:u.email,name:u.name,role:u.role})
app.post('/api/auth/login',(req,res)=>{const {email,password}=req.body||{},u=db.prepare('SELECT * FROM users WHERE email=?').get(String(email||'').toLowerCase()) as any;if(!u||u.disabled||!bcrypt.compareSync(String(password||''),u.password_hash))return res.status(401).json({error:'Неверный email или пароль'});const sid=uid();db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(sid,u.id,now()+7*864e5);res.cookie('sid',sid,{httpOnly:true,sameSite:'lax',maxAge:7*864e5});res.json({user:pub(u)})})
app.post('/api/auth/logout',auth,(req:Req,res)=>{db.prepare('DELETE FROM sessions WHERE id=?').run(req.cookies.sid);res.clearCookie('sid');res.json({ok:true})}); app.get('/api/auth/me',auth,(req:Req,res)=>res.json({user:pub(req.user)}))
app.post('/api/auth/change-password',auth,(req:Req,res)=>{const {currentPassword,newPassword}=req.body||{};if(!newPassword||String(newPassword).length<8||!bcrypt.compareSync(String(currentPassword||''),req.user.password_hash))return res.status(400).json({error:'Неверный текущий пароль или новый пароль короче 8 символов'});db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(bcrypt.hashSync(newPassword,12),req.user.id);res.json({ok:true})})
app.get('/api/users',auth,isAdmin,(req,res)=>res.json({users:db.prepare('SELECT id,email,name,role,disabled,created_at createdAt FROM users ORDER BY created_at').all()})); app.post('/api/users',auth,isAdmin,(req,res)=>{const {email,name,role='accountant',password}=req.body||{};if(!email||!name||!password||String(password).length<8)return res.status(400).json({error:'Заполните email, имя и пароль от 8 символов'});try{const id=uid();db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,?)').run(id,String(email).toLowerCase(),name,role,bcrypt.hashSync(password,12),0,now());res.status(201).json({id})}catch{return res.status(409).json({error:'Пользователь уже существует'})}}); app.patch('/api/users/:id',auth,isAdmin,(req,res)=>{const {role,disabled,name}=req.body||{};db.prepare('UPDATE users SET role=COALESCE(?,role),disabled=COALESCE(?,disabled),name=COALESCE(?,name) WHERE id=?').run(role,disabled==null?null:(disabled?1:0),name,req.params.id);res.json({ok:true})})
app.get('/api/journal',auth,(req,res)=>res.json({entries:db.prepare('SELECT data FROM journal_entries ORDER BY created_at DESC').all().map((r:any)=>JSON.parse(r.data))})); app.post('/api/journal',auth,(req,res)=>{const e=req.body;db.prepare('INSERT INTO journal_entries VALUES (?,?,?)').run(e.id,JSON.stringify(e),e.createdAt||now());res.status(201).json(e)}); app.patch('/api/journal/:id',auth,(req,res)=>{db.prepare('UPDATE journal_entries SET data=? WHERE id=?').run(JSON.stringify(req.body),req.params.id);res.json(req.body)}); app.delete('/api/journal/:id',auth,(req,res)=>{db.prepare('DELETE FROM journal_entries WHERE id=?').run(req.params.id);res.json({ok:true})})
if(process.argv.includes('--init-only'))process.exit(0); app.listen(Number(process.env.PORT||3001),()=>console.log('API listening on http://localhost:3001'))
